const dogBreeds = <String>[
  'Affenpinscher',
  'Afghanischer Windhund',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Akita',
  'American Staffordshire Terrier',
  'Amerikanischer Cocker Spaniel',
  'Amerikanischer Wasserspaniel',
  'Anatolischer Hirtenhund',
  'Appenzeller Sennenhund',
  'Australian Cattle Dog',
  'Australian Kelpie',
  'Australian Shepherd',
  'Australian Terrier',
  'Azawakh',
  'Barbet',
  'Barsoi',
  'Basenji',
  'Basset Fauve de Bretagne',
  'Basset Hound',
  'Bayerischer Gebirgsschweißhund',
  'Beagle',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Belgischer Schäferhund',
  'Bergamasker Hirtenhund',
  'Berger Blanc Suisse',
  'Berner Sennenhund',
  'Bernhardiner',
  'Bichon Frisé',
  'Biewer Terrier',
  'Bloodhound',
  'Bobtail',
  'Bologneser',
  'Border Collie',
  'Border Terrier',
  'Bordeauxdogge',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Briard',
  'Broholmer',
  'Bullmastiff',
  'Bullterrier',
  'Cairn Terrier',
  'Cane Corso Italiano',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chihuahua',
  'Chinesischer Schopfhund',
  'Chow-Chow',
  'Cirneco dell’Etna',
  'Clumber Spaniel',
  'Coton de Tuléar',
  'Curly-Coated Retriever',
  'Dackel',
  'Dalmatiner',
  'Dandie Dinmont Terrier',
  'Deerhound',
  'Deutsch Drahthaar',
  'Deutsch Kurzhaar',
  'Deutsch Langhaar',
  'Deutsche Bracke',
  'Deutsche Dogge',
  'Deutscher Jagdterrier',
  'Deutscher Pinscher',
  'Deutscher Schäferhund',
  'Deutscher Spitz',
  'Deutscher Wachtelhund',
  'Dobermann',
  'Dogo Argentino',
  'Drahthaar-Foxterrier',
  'English Cocker Spaniel',
  'English Foxhound',
  'English Pointer',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Terrier',
  'Entlebucher Sennenhund',
  'Epagneul Breton',
  'Eurasier',
  'Field Spaniel',
  'Fila Brasileiro',
  'Finnischer Lapphund',
  'Finnischer Spitz',
  'Flat-Coated Retriever',
  'Französische Bulldogge',
  'Galgo Español',
  'Golden Retriever',
  'Gordon Setter',
  'Grand Basset Griffon Vendéen',
  'Greyhound',
  'Griffon Bruxellois',
  'Großer Münsterländer',
  'Havaneser',
  'Holländischer Schäferhund',
  'Irish Red Setter',
  'Irish Terrier',
  'Irish Wolfhound',
  'Italienisches Windspiel',
  'Jack Russell Terrier',
  'Kangal-Hirtenhund',
  'Kaukasischer Owtscharka',
  'Kerry Blue Terrier',
  'King Charles Spaniel',
  'Kleiner Münsterländer',
  'Komondor',
  'Kuvasz',
  'Labrador Retriever',
  'Lagotto Romagnolo',
  'Landseer',
  'Leonberger',
  'Lhasa Apso',
  'Malteser',
  'Manchester Terrier',
  'Maremmen-Abruzzen-Schäferhund',
  'Mastiff',
  'Mittelschnauzer',
  'Neufundländer',
  'Norfolk Terrier',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Papillon',
  'Parson Russell Terrier',
  'Pekingese',
  'Petit Basset Griffon Vendéen',
  'Pharaonenhund',
  'Podenco Ibicenco',
  'Polnischer Niederlaufhund',
  'Pudel',
  'Pudelpointer',
  'Pyrenäenberghund',
  'Pyrenäenhirtenhund',
  'Rhodesian Ridgeback',
  'Riesenschnauzer',
  'Rottweiler',
  'Russischer Schwarzer Terrier',
  'Saluki',
  'Samojede',
  'Schipperke',
  'Schnauzer',
  'Schottischer Terrier',
  'Sealyham Terrier',
  'Shar Pei',
  'Shetland Sheepdog',
  'Shiba',
  'Shih Tzu',
  'Siberian Husky',
  'Skye Terrier',
  'Sloughi',
  'Spinone Italiano',
  'Staffordshire Bullterrier',
  'Sussex Spaniel',
  'Tibet-Spaniel',
  'Tibet-Terrier',
  'Tosa',
  'Weimaraner',
  'Welsh Corgi Cardigan',
  'Welsh Corgi Pembroke',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Yorkshire Terrier',
  'Zwergpinscher',
  'Zwergschnauzer',
];
