name: dogwatch_mobile
description: DogWatch Flutter app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  mobile_scanner: ^5.2.3
  webview_flutter: ^4.8.0
  advanced_searchable_dropdown: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SourGummy
      fonts:
        - asset: fonts/SourGummy-Regular.ttf
          weight: 400
        - asset: fonts/SourGummy-SemiBold.ttf
          weight: 600
        - asset: fonts/SourGummy-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: fonts/Roboto_SemiCondensed-Regular.ttf
          weight: 400
        - asset: fonts/Roboto_Condensed-SemiBold.ttf
          weight: 600
